### PR TITLE
Update dependencies

### LINKED ISSUE #82: Fix deprecation warnings
Fix as much as possible deprecation warnings shown by `python -Wa ./manage.py test`.

### LINKED ISSUE #122: Update Django to latest LTS
Update to v2.2LTS.

Will fix #76.

### PR DESCRIPTION
**Pull request by Neraste**
Updates made:

* Core updates:
  * Django to v2.2 LTS. Some breaking changes were resolved. `urls.py` now uses the new `django.urls.path` method, which is easier to write;
  * Django REST Framework to v3.11.0;
* DRF optional dependencies updates:
  * Markdown to v3.2.1;
  * Pygments to v2.5.2;
* Pytest suite updates:
  * Pytest to v5.3.5;
  * Pytest-asyncio to v0.10.0;
  * Pytest-django to v3.8.0;
  * Pytest-mock to v2.0.0;
* Other updates:
  * APScheduler to v3.6.3;
  * Django-ordered-model to v3.3.0;
  * Python-decouple to v3.3.

Channels is not updated by this PR, as the way we use it is incorrect. See #125.

Fixes #122, fixes #82.

### CODE REVIEW

**Comment by Neraste** [comment]
For now I could not update channels, as this breaks the way tests are made. I think that we may use Channels the wrong way, see the discussion of [this SO question](https://stackoverflow.com/a/53248771/4584444), and that we may have to reconsider things.

**Comment by Neraste** [comment]
I cannot understand why Codecov goes crazy about the file `dakara_server/playlist/consumers.py`. Since this involves the consumers, and since we have to rework them (see #125), I propose to ignore this failed test.

As a note, maybe we should be more tolerant for PR coverage targets.

**Comment by Nadeflore** [comment]
I think I was able to understand the problem when using a database from the old version to the new one.
The problem is that the database contains invalid foreign key constraints
The reason the problem occur only with django 2.0 is because with django 1, sqlite foreign key constrain were not enforced. See https://docs.djangoproject.com/en/3.0/releases/2.0/#foreign-key-constraints-are-now-enabled-on-sqlite

But the actual reason the database contains invalid foreign key constraints is due to a bug that was present when the database was created: https://code.djangoproject.com/ticket/29182

The bug has been fixed, but the databases generated with the django version containing the bug.
(Note that the bug report initially stated that the bug does not occur when migrating using ./manage.py migrate , but other comments reproduced the bug with it)

I'm Still trying to the best way to fix the database

**Comment by Neraste** [comment]
This is interesting. So this is defintely a bug on Django side. Maybe is it easier to create a database fix for Django 1?

**Pull request merged**
